import {io} from "socket.io-client"
export const socket = io('http://localhost:3004')
//socket io client

import NoChat from "@/components/NoChat/NoChat"
import SidebarLayout from "@/components/Layouts/SidebarLayout"
import {chatBodyState} from "@/atoms/chatBodyState"
import Hoc from "@/components/hoc/Hoc"
import Head from "next/head"
import {RecoilRoot,useRecoilValue} from "recoil"


export default function ChatRoom(){

  return(<>
   
      <Head>
        <title>Chat Room</title>
        <meta name="Chat-room" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />       
      </Head>

      <main style={{flexGrow:1,alignSelf:"center"}}>
        <NoChat/>
    </main>
    </>
)}
ChatRoom.getLayout = function getLayout(page) {
  return (
    <>
      <RecoilRoot>
        <SidebarLayout>
          {page}
        </SidebarLayout>
      </RecoilRoot>
    </>
  )
}


