import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Button from "@/components/Buttons/Button"
import girlWithLaptop from "../public/girlWithLaptop.png"
import Navbar from "@/components/nav/Navbar"
import wavesYellow from "../public/WavesYellow.png"
import circlesBg from "../public/CirclesBg.png"
import {RecoilRoot} from "recoil"

export default function Home() {
  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />       
      </Head>
      <main 
        style={{
          display:"flex",
          gap:8,
          flexDirection:"column",
          justifyContent:"center",
          alignItems:"center",
          position:"relative"}}>
        
        <Image objectFit="cover" width="400" height="400" src={girlWithLaptop}/>
        <h2 style={{fontWeight:800}}>Start chatting now</h2>
        <p>Everything you need in just one place.</p>

        <Image 
          width="1366"
          style={{
            position:"absolute",
            zIndex:-22,
            top:431}} 
          objectFit="cover" 
          
          src={wavesYellow}/>  
        
        <Image 
          style={{
            position:"absolute",
            zIndex:-100}} 
          objectFit="cover" 
          fill
          src={circlesBg}/>
        <Button><small>Get into room!</small></Button>

      </main>
    </>
  )
}
Home.getLayout = function getLayout(page) {
  return (
    <RecoilRoot>
      <div>
      <Navbar/>
      {page}
      </div>
    </RecoilRoot>
  )
}